import "./globals.css";
import { Inter } from "next/font/google";
import { FinanceHeader } from "@/components/header";
import { Toaster } from "sonner";
import SidebarUI from "./sidebar";
import Providers from "@/components/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="flex h-screen overflow-hidden w-full min-w-screen">
            <SidebarUI />
            <div className="flex flex-1 flex-col overflow-hidden w-full">
              <FinanceHeader />
              <main className="flex-1 overflow-y-auto p-8 w-full">
                {children}
              </main>
            </div>
          </div>
          <Toaster position="top-right" />
        </Providers>
      </body>
    </html>
  );
}
